version: "3.9"

networks:
  traefik_public:
    external: true
  light_wsantos_net_kafka:
    external: true
  database:
    driver: "overlay"

volumes:
  database:
    driver: "local"

services:
  level4:
    image: "registry.wsantos.net/tradingmachines/level4:latest"
    depends_on:
      - "database"
    networks:
      - "traefik_public"
      - "light_wsantos_net_kafka"
      - "database"
    # remember to remove this
#    ports:
#      - target: 5000
#        published: 5000
#        protocol: "tcp"
#        mode: "host"
    # /remember to remove this
    deploy:
      labels:
        # traefik
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_public"
        # http
        - "traefik.http.routers.level4_wsantos_net-level4.entrypoints=websecure"
        - "traefik.http.routers.level4_wsantos_net-level4.rule=Host(`level4.wsantos.net`)"
        - "traefik.http.routers.level4_wsantos_net-level4.tls.certresolver=letsencrypt"
        - "traefik.http.routers.level4_wsantos_net-level4.service=level4_wsantos_net-level4"
        - "traefik.http.routers.level4_wsantos_net-level4.middlewares=level4_wsantos_net-level4_auth"
        - "traefik.http.services.level4_wsantos_net-level4.loadbalancer.server.port=5000"
        - "traefik.http.middlewares.level4_wsantos_net-level4_auth.basicauth.users=william:$$apr1$$PwWBs2/Z$$vxn5miRORxXIFnEEl9DW31"

  database:
    image: "postgres:latest"
    networks:
      - "database"
    volumes:
      - "database:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_DB=level4"
      - "POSTGRES_USER=level4"
      - "POSTGRES_PASSWORD=level4"
      - "POSTGRES_HOST_AUTH_METHOD=password"
