version: "3.9"

services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    ports:
      - "2181:2181"
    environment:
      - "ALLOW_ANONYMOUS_LOGIN=yes"

  kafka:
    image: "bitnami/kafka:3.4"
    ports:
      - "9092:9092"
    environment:
      - "KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181"
      - "ALLOW_PLAINTEXT_LISTENER=yes"
      - "KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092"
    depends_on:
      - "zookeeper"

  kafka-ui:
    image: "provectuslabs/kafka-ui:latest"
    ports:
      - "8080:8080"
    environment:
      - "KAFKA_CLUSTERS_0_NAME=local"
      - "KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181"
      - "KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092"
    depends_on:
      - "kafka"
